version: '3.8'

services:
  postgres-course:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network

  pgadmin-course:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "glauber.jordao1995@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres-course
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge